#!/bin/bash
set -e
if [ "$pwrrt_xtrace" != "" ]; then
  set -o xtrace
fi

# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
        if [ -d /usr/doc -a ! -e /usr/doc/pwrtest -a -d /usr/share/doc/pwrtest ]; then
                ln -sf ../share/doc/pwrtest /usr/doc/pwrtest
        fi
fi
# End automatically added section

proot="/pwrp"
aroot="/usr/pwrp/adm"

# Create users...
new_user=0
if getent group pwrp > /dev/null; then
  echo "-- group pwrp already exist"
else
  if groupadd pwrp; then
    echo "-- group pwrp added"
  fi
fi

if getent group b55 > /dev/null; then
  echo "-- group b55 already exist"
else
  if groupadd b55; then
    echo "-- group b55 added"
  fi
fi

if getent group b66 > /dev/null; then
  echo "-- group b66 already exist"
else
  if groupadd b66; then
    echo "-- group b66 added"
  fi
fi

if getent group skiftel > /dev/null; then
  echo "-- group skiftel already exist"
else
  if groupadd skiftel; then
    echo "-- group skiftel added"
  fi
fi



if getent passwd pwrp > /dev/null; then
  echo "-- user pwrp already exist"
else
  new_user=1

  if useradd -s /bin/bash -p aaupl/kQs1p3U -g pwrp -G b55,b66,skiftel -d /home/pwrp pwrp; then
    echo "-- user pwrp added"
  fi
  if [ ! -e /home/pwrp ]; then
    mkdir /home/pwrp
    cp /usr/pwrsev/cnf/user/.bashrc /home/pwrp
    cp /usr/pwrsev/cnf/user/.bash_profile /home/pwrp
#    cp /usr/pwrsev/cnf/user/.mwmrc /home/pwrp
    cp /usr/pwrsev/cnf/user/.rtt_start /home/pwrp
    chmod a+x /home/pwrp/.rtt_start
    cp /usr/pwrsev/cnf/user/.xtt_start /home/pwrp
    chmod a+x /home/pwrp/.xtt_start
#    cp /usr/pwrsev/cnf/user/.xsession /home/pwrp

    chown -R pwrp /home/pwrp
    chgrp -R pwrp /home/pwrp
  fi

  # Add to group dialout
  if getent group dialout > /dev/null; then
    usermod -a -G dialout pwrp
  fi
fi

if getent passwd skiftel > /dev/null; then
  echo "-- user skiftel already exist"
else
  new_user=1

  if useradd -s /bin/bash -p aa6NzxS/aBgP6 -g skiftel -G pwrp -d /home/skiftel skiftel; then
    echo "-- user skiftel added"
  fi

  if [ ! -e /home/skiftel ]; then
    mkdir /home/skiftel
    cp /usr/pwrsev/cnf/user/.bashrc /home/skiftel
    cp /usr/pwrsev/cnf/user/.bash_profile /home/skiftel
#    cp /usr/pwrsev/cnf/user/.mwmrc /home/skiftel
    cp /usr/pwrsev/cnf/user/.rtt_start /home/skiftel
    chmod a+x /home/skiftel/.rtt_start
    cp /usr/pwrsev/cnf/user/.xtt_start /home/skiftel
    chmod a+x /home/skiftel/.xtt_start
#    cp /usr/pwrsev/cnf/user/.xsession /home/skiftel

    chown -R pwrp /home/skiftel
    chgrp -R pwrp /home/skiftel
  fi
fi

if getent passwd b55 > /dev/null; then
  new_user=1

  # Check if group audio exist
  if getent group audio > /dev/null; then
    groups="pwrp,audio"
  else
    groups="pwrp"
  fi

  if useradd -s /bin/bash -p aaQPClsglxJP6 -g b55 -G $groups -d /home/b55 b55; then
    echo "-- user b55 added"
  fi
  if [ ! -e /home/b55 ]; then
    mkdir /home/b55
    cp /usr/pwrsev/cnf/op/.bashrc /home/b55
    cp /usr/pwrsev/cnf/op/.bash_profile /home/b55
#    cp /usr/pwrsev/cnf/op/.mwmrc /home/b55
    cp /usr/pwrsev/cnf/op/.rtt_start /home/b55
    chmod a+x /home/b55/.rtt_start
    cp /usr/pwrsev/cnf/op/.xtt_start /home/b55
    chmod a+x /home/b55/.xtt_start
#    cp /usr/pwrsev/cnf/op/.xsession /home/b55

    chown -R b55 /home/b55
    chgrp -R pwrp /home/b55
    chmod g+rwx /home/b55
  fi
fi

if getent passwd b66 > /dev/null; then
  new_user=1

  # Check if group audio exist
  if getent group audio > /dev/null; then
    groups="pwrp,audio"
  else
    groups="pwrp"
  fi

  if useradd -s /bin/bash -p aae.nHgHbfUpw -g b66 -G $groups -d /home/b66 b66; then
    echo "-- user b66 added"
  fi
  if [ ! -e /home/b66 ]; then
    mkdir /home/b66
    cp /usr/pwrsev/cnf/op/.bashrc /home/b66
    cp /usr/pwrsev/cnf/op/.bash_profile /home/b66
#    cp /usr/pwrsev/cnf/op/.mwmrc /home/b66
    cp /usr/pwrsev/cnf/op/.rtt_start /home/b66
    chmod a+x /home/b66/.rtt_start
    cp /usr/pwrsev/cnf/op/.xtt_start /home/b66
    chmod a+x /home/b66/.xtt_start
#    cp /usr/pwrsev/cnf/op/.xsession /home/b66

    chown -R b66 /home/b66
    chgrp -R pwrp /home/b66
    chmod g+rwx /home/b66
  fi
fi

chown -R pwrp /usr/pwrsev
chgrp -R pwrp /usr/pwrsev

chmod u+s /usr/pwrsev/exe/sev_ini
chown root /usr/pwrsev/exe/rt_prio
chmod u+s /usr/pwrsev/exe/rt_prio

# Copy configuration files
new_cnf=0
if [ ! -e /etc/proview.cnf ]; then
  cp /usr/pwrsev/cnf/proview.cnf /etc
  new_cnf=1
fi

# Add pwrp_profile to profile
if ! grep -q "/etc/pwrp_profile\b" /etc/profile; then
  cat >> /etc/profile <<-EOF
	if [ -e /etc/pwrp_profile ]; then
	  source /etc/pwrp_profile
	fi
EOF
fi

# Create startup link
set +e
checklink=`eval ls /etc/rc2.d/S90pwrsev 2>/dev/null`
set -e
if [ "$checklink" != "" ]; then
  rm /etc/rc2.d/S90pwrsev
fi
ln -s /etc/init.d/pwrsev /etc/rc2.d/S90pwrsev

# Create project
new_project=0
if [ ! -e $proot ]; then
  new_project=1

  mkdir $proot
  mkdir $proot/common
  mkdir $proot/common/inc
  mkdir $proot/common/load
  mkdir $proot/common/log
  mkdir $proot/common/loghist
  mkdir $proot/common/db
  mkdir $proot/common/web
  mkdir $proot/x86_linux
  mkdir $proot/x86_linux/exe
  mkdir $proot/x86_linux/lib
  mkdir $proot/x86_linux/obj
  mkdir $proot/x86_linux/lis

  chown -R pwrp $proot
  chgrp -R pwrp $proot
  
fi

if [ ! -e $aroot/db ]; then
  mkdir -p $aroot/db
  chown -R pwrp $aroot
fi

#

changes=0
if [ $new_user -eq 1 ]; then
  changes=1
elif [ $new_cnf -eq 1 ]; then
  changes=1
elif [ $new_project -eq 1 ]; then
  changes=1
fi

if [ $changes -ne 0 ]; then
  echo ""
  echo ""
  echo "***********************************************************"
  echo "  Don't forget to do this :"
  echo ""
fi

if [ $new_cnf -eq 1 ]; then
  echo "-- Enter QcomBusId in /etc/proview.cnf"
fi

#if [ $new_user -eq 1 ]; then
#  echo "-- Enter OpPlace object as argument to rt_xtt in /home/b55/.xtt_start"
#fi

if [ $new_project -eq 1 ]; then
  nodename=`eval uname -n`
  echo "-- Create file /home/pwrp/.rhosts"
  echo "-- Distribute project to $nodename"
fi

if [ $changes -ne 0 ]; then
  echo ""
  echo "***********************************************************"
  echo ""
fi











