.TH sev_xtt "1" "April 2005" "Proview" "Proview Manual"
.SH NAME
sev_xtt - Proview Storage Operator
.SH SYNOPSIS
.B sev_xtt 
[\fIOPTION\fR] [opplace]
.SH DESCRIPTION
The Proview Storage Operator Environment contains a set of utitlities to handle the
the stored data.

.SH OPTIONS
.HP
\fBopplace\fR
.IP
The name of the OpPlace object for the operator place.

.HP
\fB\-l\fR
.IP
Language. 

.RS
en_us  English
.RE
.RS
sv_se  Swedish.
.RE
.RS
de_de  German.
.RE

.RS
en_us is default.
.RE
.HP
\fB\-q\fR
.IP
Quiet. Hide license information.
.SH AUTHOR
Written by cs.
.SH "SEE ALSO"
.BR sevpwr(1),
.BR sev_ini(1)







