/** 
 * Proview   Open Source Process Control.
 * Copyright (C) 2005-2012 SSAB EMEA AB.
 *
 * This file is part of Proview.
 *
 * This program is free software; you can redistribute it and/or 
 * modify it under the terms of the GNU General Public License as 
 * published by the Free Software Foundation, either version 2 of 
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with Proview. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking Proview statically or dynamically with other modules is
 * making a combined work based on Proview. Thus, the terms and 
 * conditions of the GNU General Public License cover the whole 
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * Proview give you permission to, from the build function in the
 * Proview Configurator, combine Proview with modules generated by the
 * Proview PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every 
 * copy of the combined work is accompanied by a complete copy of 
 * the source code of Proview (the version used to produce the 
 * combined work), being distributed under the terms of the GNU 
 * General Public License plus this exception.
 **/

#ifndef wb_bckw_gtk_h
#define wb_bckw_gtk_h

/* wb_bckw_gtk.h -- Backupfile display window */

#ifndef wb_bckw_h
# include "wb_bckw.h"
#endif

#ifndef cow_wow_gtk_h
# include "cow_wow_gtk.h"
#endif

#include <gtk/gtk.h>

class WbBckWGtk : public WbBckW {
  public:
    WbBckWGtk(
	void *l_parent_ctx,
	GtkWidget *l_parent_wid,
	ldh_tSession l_ldhses,
	const char *l_name,
	wb_bck_list *l_list,
	int l_editmode,
	pwr_tStatus *status);
    ~WbBckWGtk();

    GtkWidget		*parent_wid;
    GtkWidget		*toplevel;
    GtkWidget		*form;
    GtkWidget		*nav_widget;
    GtkWidget		*file_transfer_wb;
    GtkWidget		*edit_check_all;
    GtkWidget		*edit_check_clear;
    CoWowFocusTimerGtk  focustimer;
    CoWowFocusTimerGtk	maptimer;

    void print();
    void set_title( char *title);

    static gboolean action_inputfocus( GtkWidget *w, GdkEvent *event, gpointer data);
    static void activate_exit( GtkWidget *w, gpointer data);
    static void activate_print( GtkWidget *w, gpointer data);
    static void activate_open( GtkWidget *w, gpointer data);
    static void activate_diff( GtkWidget *w, gpointer data);
    static void activate_diff_wb( GtkWidget *w, gpointer data);
    static void activate_transfer_wb( GtkWidget *w, gpointer data);
    static void activate_filter( GtkWidget *w, gpointer data);
    static void activate_check_all( GtkWidget *w, gpointer data);
    static void activate_check_clear( GtkWidget *w, gpointer data);
    static void activate_zoom_in( GtkWidget *w, gpointer data);
    static void activate_zoom_out( GtkWidget *w, gpointer data);
    static void activate_zoom_reset( GtkWidget *w, gpointer data);
    static void activate_help( GtkWidget *w, gpointer data);

};

#endif









