
        .facility       CNV,314 /prefix = CNV__ ! 

success 	<successful completion>				/succ
syntax		<Syntax error in conversion definition table, '%s'> /error
nopartype	<No such parameter type, '%s'>			/error
convtype	<Type of conversion not supported, Param: '%s'>	/error
nofile		<Unable to open file, '%s'>			/error
nomemory 	<Unable allocate dynamic memory>		/error
filesize	<To many rows in conversion definition file>	/error
convdeftype 	<ConvDefType not defined>			/error
class		<ConvDef is not a class object>			/error
convdefclass	<Error creating conversion table from class, Reason: >	/error
convdeffile	<Error creating conversion table from file, Reason: >	/error
convdefobject	<Error creating conversion table from object, Reason: >	/error
