
        .facility       TLOG,311 /prefix = TLOG__ ! 

success 	<successful completion>				/succ
nomemory	<nomemory>					/error
confobjnotfound	<tlog configure object not found>		/error
userobjnotfound	<tlog user object not found>			/error
maxmodify	<maximum amount of modify levels reached>	/error
notsel		<object not in selectlist>			/error
fileopen	<unable to open file '%s'>			/error
difftext	<difference in text>				/error
diffattr	<difference in attrbute>			/error
difftime	<difference in time>				/error
listend		<end of list>					/info
timesyntax	<syntax error in time>				/error
time_gt		<time greater than>				/info
time_lt		<time less than>				/info
time_eq		<time equal>					/info
beforequal	<syntax error in before time>			/error
sincequal	<syntax error in since time>			/error
