/* 
 * Proview   Open Source Process Control.
 * Copyright (C) 2005-2011 SSAB Oxelosund AB.
 *
 * This file is part of Proview.
 *
 * This program is free software; you can redistribute it and/or 
 * modify it under the terms of the GNU General Public License as 
 * published by the Free Software Foundation, either version 2 of 
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with Proview. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking Proview statically or dynamically with other modules is
 * making a combined work based on Proview. Thus, the terms and 
 * conditions of the GNU General Public License cover the whole 
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * Proview give you permission to, from the build function in the
 * Proview Configurator, combine Proview with modules generated by the
 * Proview PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every 
 * copy of the combined work is accompanied by a complete copy of 
 * the source code of Proview (the version used to produce the 
 * combined work), being distributed under the terms of the GNU 
 * General Public License plus this exception.
 */

#include <float.h>
#include <string.h>
#include <iconv.h>
#include "co_cnv.h"

char *cnv_iso8859_to_utf8( char *iso, size_t iso_size)
{
  static iconv_t cd = 0;
  static char utf8[2048];
  char *utf8p = utf8;
  size_t utf8_size = sizeof(utf8);
  
  if ( !cd)
    cd = iconv_open( "UTF-8", "ISO8859-1");

  if ( iconv( cd, &iso, &iso_size, &utf8p, &utf8_size) == (size_t)(-1))
    strcpy( utf8, "");

  return utf8;
}

char *cnv_utf8_to_iso8859( char *utf8, size_t utf8_size)
{
  static iconv_t cd = 0;
  static char iso[2048];
  char *isop = iso;
  size_t iso_size = sizeof(iso);
  
  if ( !cd)
    cd = iconv_open( "ISO8859-1", "UTF-8");

  if ( iconv( cd, &utf8, &utf8_size, &isop, &iso_size) == (size_t)(-1))
    strcpy( iso, "");

  return iso;
}
