
        .facility       FLOW,305 /prefix = FLOW__ ! 

success 	<successful completion>				/succ
noelem		<No such element> 				/error
nonext		<There is no next element>			/error
noprevious	<There is no previous element>			/error
noparent	<There is no parent>				/error
noconpoint	<There is no such conpoint>			/error
nochild		<There is no child>				/error
nonextsibling	<There is no next sibling>			/error
destroyed       <Flow ctx is destoryed>                         /info
no_propagate    <Don't propagate event handling>                /info
fileopen        <Unable to open file>                           /error