ARG RELEASE=debian:10
FROM $RELEASE

ENV DISPLAY :1
ENV DEBIAN_FRONTEND none_interactive

COPY ./pwrtest02/create_project.sh ./pwrtest02/configure_cvolpwrtest02.pwr_com ./pwrtest02/configure_directory.pwr_com ./pwrtest02/configure_volpwrtest02.pwr_com ./data/pwrtest02.tar.gz ./pwrtest02/wa_testall.sh ./dummy_display_xorg.conf ./
RUN ./create_project.sh create
