#!/bin/sh
set -e

# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
        if [ -d /usr/doc -a ! -e /usr/doc/pwrtest -a -d /usr/share/doc/pwrtest ]; then
                ln -sf ../share/doc/pwrtest /usr/doc/pwrtest
        fi
fi
# End automatically added section

proot="/pwrp"
aroot="/pwrp/adm"

# Create users...
new_user=0
if ! grep -q "\bpwrp:" /etc/group; then
  echo "-- Add group pwrp"
  groupadd pwrp
fi
if ! grep -q "\bb55:" /etc/group; then
  echo "-- Add group b55"
  groupadd b55
fi
if ! grep -q "\bskiftel:" /etc/group; then
  echo "-- Add group skiftel"
  groupadd skiftel
fi

if ! grep -q "\bpwrp:" /etc/passwd; then
  echo "-- Add user pwrp"
  new_user=1
  useradd -s /bin/bash -p aaupl/kQs1p3U -g pwrp -G b55,skiftel -d /home/pwrp pwrp
  if [ ! -e /home/pwrp ]; then
    mkdir /home/pwrp
    cp /usr/pwrrt/cnf/user/.bashrc /home/pwrp
    cp /usr/pwrrt/cnf/user/.bash_profile /home/pwrp
    cp /usr/pwrrt/cnf/user/.mwmrc /home/pwrp
    cp /usr/pwrrt/cnf/user/.rtt_start /home/pwrp
    cp /usr/pwrrt/cnf/user/.xtt_start /home/pwrp
    cp /usr/pwrrt/cnf/user/.xsession /home/pwrp

    chown -R pwrp /home/pwrp
    chgrp -R pwrp /home/pwrp
  fi
fi

if ! grep -q "\bskiftel:" /etc/passwd; then
  echo "-- Add user skiftel"
  new_user=1
  useradd -s /bin/bash -p aa6NzxS/aBgP6 -g skiftel -G pwrp -d /home/skiftel skiftel
  if [ ! -e /home/pwrp ]; then
    mkdir /home/skiftel
    cp /usr/pwrrt/cnf/user/.bashrc /home/skiftel
    cp /usr/pwrrt/cnf/user/.bash_profile /home/skiftel
    cp /usr/pwrrt/cnf/user/.mwmrc /home/skiftel
    cp /usr/pwrrt/cnf/user/.rtt_start /home/skiftel
    cp /usr/pwrrt/cnf/user/.xtt_start /home/skiftel
    cp /usr/pwrrt/cnf/user/.xsession /home/skiftel

    chown -R pwrp /home/skiftel
    chgrp -R pwrp /home/skiftel
  fi
fi

if ! grep -q "\bb55:" /etc/passwd; then
  echo "-- Add user b55"
  new_user=1
  useradd -s /bin/bash -p aaQPClsglxJP6 -g b55 -G pwrp -d /home/b55 b55
  if [ ! -e /home/b55 ]; then
    mkdir /home/b55
    cp /usr/pwrrt/cnf/op/.bashrc /home/b55
    cp /usr/pwrrt/cnf/op/.bash_profile /home/b55
    cp /usr/pwrrt/cnf/op/.mwmrc /home/b55
    cp /usr/pwrrt/cnf/op/.rtt_start /home/b55
    cp /usr/pwrrt/cnf/op/.xtt_start /home/b55
    cp /usr/pwrrt/cnf/op/.xsession /home/b55

    chown -R b55 /home/b55
    chgrp -R pwrp /home/b55
  fi
fi

chown -R pwrp /usr/pwrrt
chgrp -R pwrp /usr/pwrrt

chmod u+s /usr/pwrrt/exe/rt_ini
chmod u+s /usr/pwrrt/exe/rt_rtt
chmod u+s /usr/pwrrt/exe/rt_xtt
chmod u+s /usr/pwrrt/exe/rt_bck

# Copy configuration files
new_cnf=0
if [ ! -e /etc/proview.cnf ]; then
  cp /usr/pwrrt/cnf/proview.cnf /etc
  new_cnf=1
fi

# Add pwrp_profile to profile
if ! grep -q "/etc/pwrp_profile\b" /etc/profile; then
  cat >> /etc/profile <<-EOF
	if [ -e /etc/pwrp_profile ]; then
	  source /etc/pwrp_profile
	fi
EOF
fi

# Create startup link
if [ -e /etc/rc2.d/S90pwr ]; then
  rm /etc/rc2.d/S90pwr
fi
ln -s /etc/init.d/pwr /etc/rc2.d/S90pwr

if [ -e /etc/rc2.d/S90gdhserver ]; then
  rm /etc/rc2.d/S90gdhserver
fi
ln -s /etc/init.d/gdhserver /etc/rc2.d/S90gdhserver

# Create project
new_project=0
if [ ! -e $proot ]; then
  new_project=1

  mkdir $proot
  mkdir $proot/common
  mkdir $proot/common/inc
  mkdir $proot/common/load
  mkdir $proot/common/log
  mkdir $proot/common/db
  mkdir $proot/common/web
  mkdir $proot/x86_linux
  mkdir $proot/x86_linux/exe
  mkdir $proot/x86_linux/lib
  mkdir $proot/x86_linux/obj
  mkdir $proot/x86_linux/lis

  chown -R pwrp $proot
  chgrp -R pwrp $proot
fi

if [ ! -e $aroot/db ]; then
  mkdir -p $aroot/db
  chown -R pwrp $aroot
fi

# Copy jar-files to web directory
if [ -e /etc/proview.cnf ]; then
  web_dir=`eval cat /etc/proview.cnf | grep "\\bwebDirectory\\b" | awk '{print $2}'`

  if [ -e "$web_dir" ]; then
    cp /usr/pwrrt/lib/pwr_rt_client.jar $web_dir
    cp /usr/pwrrt/lib/pwr_jop.jar $web_dir
  fi
fi


changes=0
if [ $new_user -eq 1 ]; then
  changes=1
elif [ $new_cnf -eq 1 ]; then
  changes=1
elif [ $new_project -eq 1 ]; then
  changes=1
fi

if [ $changes -ne 0 ]; then
  echo ""
  echo ""
  echo "***********************************************************"
  echo "  Don't forget to do this :"
  echo ""
fi

if [ $new_cnf -eq 1 ]; then
  echo "-- Enter QcomBusId in /etc/proview.cnf"
fi

if [ $new_user -eq 1 ]; then
  echo "-- Enter OpPlace object as argument to rt_xtt in /home/b55/.xtt_start"
fi

if [ $new_project -eq 1 ]; then
  echo "-- Create file /home/pwrp/.rhost"
  echo "-- Copy loadfiles and applications to project"
fi

if [ $changes -ne 0 ]; then
  echo ""
  echo "***********************************************************"
  echo ""
fi











