.TH pwr "1" "April 2005" "Proview" "Proview Manual"
.SH NAME
pwr - start and stop Proview runtime environment
.SH SYNOPSIS
.B pwr 
[start][stop][restart]
.SH DESCRIPTION
Start and stop command for Proview runtime environment.

.SH OPTIONS
.HP
\fBstart\fR
.IP
Start Proview runtime environment.

.HP
\fBstop\fR
.IP
Stop Proview runtime environment.

.HP
\fBrestart\fR
.IP
First stop and then start the Proview runtime environment.

.SH FILES
/etc/pwrp_profile

The Proview system wide configuration file.

.SH ENVIRONMENT
.HP
PWR_BUS_ID
.IP
QCOM bus identity.
.SH AUTHOR
Written by UL.

.SH "SEE ALSO"
.BR rt_ini(1)

