/* 
 * Proview   Open Source Process Control.
 * Copyright (C) 2005-2014 SSAB EMEA AB.
 *
 * This file is part of Proview.
 *
 * This program is free software; you can redistribute it and/or 
 * modify it under the terms of the GNU General Public License as 
 * published by the Free Software Foundation, either version 2 of 
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with Proview. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking Proview statically or dynamically with other modules is
 * making a combined work based on Proview. Thus, the terms and 
 * conditions of the GNU General Public License cover the whole 
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * Proview give you permission to, from the build function in the
 * Proview Configurator, combine Proview with modules generated by the
 * Proview PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every 
 * copy of the combined work is accompanied by a complete copy of 
 * the source code of Proview (the version used to produce the 
 * combined work), being distributed under the terms of the GNU 
 * General Public License plus this exception.
 **/

#ifndef wb_goec_h
#define wb_goec_h

#ifndef wb_gre_h
#include "wb_gre.h"
#endif


int
goec_con_draw(
  WGre          *gre,
  vldh_t_con    con_object,
  int           create_flag,
  vldh_t_node   node
);

int
goec_con_delete( 
  WGre         *gre,
  vldh_t_con   con_object
);

int
goec_con_delete_noredraw( 
  WGre          *gre,
  vldh_t_con   con_object
);

int
goec_con_sethighlight(
  WGre            *gre,
  vldh_t_con      con_object,
  unsigned long   highlight_flag
);

int
goec_con_gethighlight(
  WGre             *gre,
  vldh_t_con       con_object,
  unsigned long   *highlight_flag
);

int
goec_con_draw_ref( 
  WGre          *gre,
  vldh_t_con    con_object,
  int           create_flag,
  vldh_t_node   node
);

int
goec_get_refnodetypeid(
  WGre             *gre,
  unsigned long   *refnode_type_id
);

int
goec_con_delete_ref( 
  WGre         *gre,
  vldh_t_con   con_object
);

int
goec_con_delete_ref_noredraw(
  WGre         *gre,
  vldh_t_con   con_object
);

int
goec_con_redraw_ref(
  WGre          *gre,
  vldh_t_node   node
);

int
goec_con_reconfig_ref(
  WGre          *gre,
  vldh_t_node   node
);

int
goec_conpoint_get_refcons( 
  vldh_t_node      node,
  unsigned long    point,
  unsigned long    flag,
  unsigned long   *cons
);

#endif
