!  rt_ds_msg.msg -- <short description>
!
!  PROVIEW/R
!  Copyright (C) 1996,98 by Mandator AB.
!
!  <Description>.
!
.facility	DS,210 /prefix = DS__		! Data Storage

success		<normal, successful completion>				/succ
noobject 	<no ds object on this node>				/error
errtypelis 	<get typelist>						/error
errtype 	<invalid datatype>					/error
erralloc 	<allocatedynamic memory>				/fatal
error		<%s>							/error
log		<%s>							/info
errorf		<%s>							/error
logf		<%s>							/info

.end
