!  rt_hash_msg.msg -- <short description>
!
!  PROVIEW/R
!  Copyright (C) 1996 by Comator Process AB.
!
!  <Description>.
!
	.facility	HASH,111/prefix=HASH__

nyi		<function not yet implemeted>				/error
bugcheck	<unrecoverable error>					/fatal
success		<succesful completion>					/succ
notfound	<entry not found>					/error
duplicate	<duplicate entry>					/error
full		<no free slot>						/error

	.end
