!  rt_pb_msg.msg -- <short description>
!
!  PROVIEW/R
!  Copyright (C) 1996 by Comator Process AB.
!
!  <Description>.
!
.facility       PB,141 /prefix = PB__		! Profibus I/O

success		<normal, successful completion>				/succ
normal		<normal operating state>				/succ
initfail	<failed to initialize slave or module>			/error
disabled	<slave is disabled>					/warning
noconn		<no connection to slave>				/error
.end


