!  rt_qdb_msg.msg -- <short description>
!
!  PROVIEW/R
!  Copyright (C) 1997,98 by Mandator AB.
!
!  <Description>.
!
.facility	QDB,18 /prefix = QDB__

success		<successful completion>					/succ
lockcheck	<database locking bugckeck>				/fatal
mutexinit	<failed to init mutex>					/error
dupladd		<item is already added>					/error
insvirmem	<insufficient virtual memory>				/error
alradd		<item is already added>					/info
linked		<buffer is linked>					/error
alrcre		<database is already created>				/error
alrmap		<database is already mapped>				/error
net_send	<error sending to network>				/error

.end
