! 
!  Proview   $Id: rt_sev_msg.msg,v 1.1 2008-07-17 11:38:21 claes Exp $
!  Copyright (C) 2005 SSAB Oxelösund AB.
!
!  This program is free software; you can redistribute it and/or 
!  modify it under the terms of the GNU General Public License as 
!  published by the Free Software Foundation, either version 2 of 
!  the License, or (at your option) any later version.
!
!  This program is distributed in the hope that it will be useful 
!  but WITHOUT ANY WARRANTY; without even the implied warranty of 
!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
!  GNU General Public License for more details.
!
!  You should have received a copy of the GNU General Public License 
!  along with the program, if not, write to the Free Software 
!  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
!
!  rt_sev_msg.msg -- <short description>
!
.facility       SEV,25 /prefix = SEV__

success		<Successful completion>					/succ
dberror		<Database error>					/error
nosuchitem	<No such item exists>					/error
nosuchnode	<No such node exists>					/error
curvetype	<Uable to draw a curve for this type>			/error
nodatatime	<No data found in this time interval>			/error
noitems		<No items found>					/error
.end




