!  rt_utl_msg.msg -- <short description>
!
!  PROVIEW/R
!  Copyright (C) 1996,98 by Mandator AB.
!
!  <Description>.
!
.facility       UTL,12 /prefix = UTL__	! Utility packages

success		<successful completion>					/succ
noslot		<pool directory full>					/fatal
badseg		<invalid pool reference>				/fatal
segsize		<invalid pool reference>				/fatal
nomark		<invalid pool reference>				/fatal
remapnyi	<remap needed, not implemented>				/fatal
bugcheck	<internal consistency error>				/fatal
malloc		<malloc error>						/fatal

.end
