
        .facility       XNAV,307 /prefix = XNAV__ ! 

success 	<successful completion>				/succ
holdcommand	<keep command mode>				/info
noelement	<element is missing>				/error
privattr	<attribute is private or virtual>		/error
eof		<end of file>					/error
nofile		<unable to open file>				/error
objectnotfound	<Object is not found>				/error
nocrossref	<No crossreferenses for this object>		/info
entryalreadyexist <Entry already exist>				/error
nouser		<Invalid user object>				/error
notconnected	<Not connected to jop process>			/error
nochild		<Object has no children>			/info
nomemory        <No virtual memory>                             /error
nochange        <Attribute can't be changed>                    /error
noselect        <Nothing is selected>                           /error
ismountobject	<Object is mountobject>				/error
nomatch		<No match in search expression>			/error
nosearch	<Search not started>				/error
searchcompile	<Can't compile search string>			/error
syntax          <Syntax error>                                  /error
trendconfig	<Error in trend configuration>			/error
nomethod	<Method not found>				/error
invisible	<Menu button invisible>				/error
insensitive	<Menu button not sensitive>			/info
notraceattr     <No trace attribute for this class>             /error
input_syntax	<Input syntax>					/error
objnotfound	<Object is not found>				/error
stringtolong	<String is too long>				/error
fastconfig	<Error in fast configuration>			/error








