!  co_cdh_msg.msg -- class definition handler messages
!
!  PROVIEW/R
!  Copyright (C) 1996 by Comator Process AB.
!
!  This module contains the defintion of the error messages used
!  in cdh modules.
!
.facility       CDH,100 /prefix = CDH__	

success		<successful completion>					/succ
invdeltatime	<invalid delta time format>				/error
invtime		<invalid time format>					/error
invtype		<invalid type>						/error
invbool		<invalid boolean format>				/error
invfloat32	<invalid float 32-bit format>				/error
invfloat64	<invalid float 64-bit format>				/error
invint8		<invalid integer 8-bit format>				/error
invint16	<invalid integer 16-bit format>				/error
invint32	<invalid integer 32-bit format>				/error
invuint8	<invalid unsigned integer 8-bit format>			/error
invuint16	<invalid unsigned integer 16-bit format>		/error
invuint32	<invalid unsigned integer 32-bit format>		/error
invcid		<invalid class identifier format>			/error
invsid		<invalid subscription identifier format>		/error
invdid		<invalid direct link identifier format>			/error
invtid		<invalid type identifier format>			/error
invvid		<invalid volume identifier format>			/error
invoix		<invalid object index format>				/error
seglen		<name segment is too long>				/error
namelen		<name is too long>					/error
noname		<no name is given>					/error
invchar		<invalid character>					/error
invid		<invalid identifier>					/error
invidchar	<invalid identifier character>				/error
invsyntax	<invalid syntax>					/error
invtypename	<invalid type name>					/error
invattrname	<invalid attribute name>				/error
invbid		<invalid body identifier>				/error
invattrindex	<invalid attribute index>				/error
