!  co_dbs_msg.msg -- database snapshot messages
!
!  PROVIEW/R
!
!  This module contains the defintion of the error messages used
!  in dbs modules.
!
.facility       DBS,107 /prefix = DBS__	

success		<successful completion>					/succ
pdrfile		<pdr_dbs_sFile failed>					/error
notmapped	<snapshot file is not mapped>				/error
badsect		<section does not exist>				/error
badoffs		<offset is out of scope>				/error
nosuchbody	<no such body exists>					/error
