!  co_nav_msg.msg -- class definition handler message
!
!  PROVIEW/R
!  Copyright (C) 1996 by Comator Process AB.
!
!  This module contains the defintion of the error messages used
!  in ccm modules.
!
.facility       NAV,106 /prefix = NAV__	

success		<successful completion>					/succ
nofile		<unable to open file>					/error
topicnotfound	<topic not found>					/error
eof             <end of file>                                           /error
objectnotfound  <object not found>					/error
nocrossref	<no crossreferences>					/error
stringnotfound	<string not found>					/error
functionnotfound <functionnotfound>					/error
