!  co_tree_msg.msg -- binary tree table
!
!  PROVIEW/R
!  Copyright (C) 2002 by Cell Network AB.
!
!  This module contains the defintion of the error messages used
!  in tree modules.
!
.facility       TREE,106 /prefix = TREE__	

success		<successful completion>					/succ
found		<key was found>						/succ
inserted	<key not present, inserted>				/succ
notfound	<key was not found>					/error
insvirmem	<insufficient virtual memory>				/error
error		<an error occurred>					/error
