!  co_time_msg.msg -- common time messages
!
!  PROVIEW/R
!  Copyright (C) 1996 by Comator Process AB.
!
!  This module contains the defintion of the error messages used
!  in co_time module.
!
.facility       TIME,101 /prefix = TIME__	

success		<successful completion>					/succ
range		<invalid range>						/error
type		<invalid type>						/error
ivtime		<invalid time>						/error
ivdtime		<invalid delta time>					/error
negtime		<negative time>						/info
