!  co_user_msg.msg -- class definition handler messages
!
!  PROVIEW/R
!  Copyright (C) 1996 by Comator Process AB.
!
!  This module contains the defintion of the error messages used
!  in user modules.
!
.facility       USER,104 /prefix = USER__	

success		<successful completion>					/succ
invsysname	<invalid system name>					/error
nosuchsystem	<no such system>					/error
nosuchuser	<no such user>						/error
notauthorized	<user is not authorized>				/error
useralrexist	<user already exist>					/error
systemalrexist	<system already exist>					/error
fileopen	<unable to open user database>				/error
