
        .facility       GE,306 /prefix = GE__ ! 

success 	<successful completion>				/succ
noattrsel	<No attribute is selectted> 			/error
attrnoedit	<Attribute is noedit>				/error
objnotfound	<Object is not found>				/error
stringtolong	<String is too long>				/error
input_syntax	<Input syntax error>				/error
noselect	<No object is selected>				/error
manyselect	<More than one object is selected>		/error
syntax		<Syntax error>					/error
qual		<Qualifier required>				/error
filename	<Error in filename>				/error
subgraphload	<Unable to load subgraph>			/error
noname		<Graph has no name>				/error
coordinate	<Invalid coordinate>				/error
current_type	<Current object is of wrong type>		/error
nocurrent	<No current object>				/error
noattr		<No such attribute>				/error
groupdyndata    <Group has dynamic data>                        /info       
recalldata_found <Data for group found in recall buffer>        /info
nonodeobject    <Can't find $Node object>                       /error
nowebhandler    <Can't find WebHandler object in this volume>   /error
webhandlers     <More than one WebHandler object found>         /error
noaccess        <Operation is not authorized>                   /error
nosubgraph	<Subgraph not found>				/error
javac		<Java compilation errors>			/error
nofile 		<File not found>				/error
nosize		<Size not found>				/error







