/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2019 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#ifndef simul_h
#define simul_h

#include "rt_plc.h"
#include "pwr_simulclasses.h"

void Sim_SigGen_exec(plc_sThread* tp, pwr_sClass_Sim_SigGen* plc_obj);
void Sim_Integrator_exec(plc_sThread* tp, pwr_sClass_Sim_Integrator* plc_obj);
void Sim_LagFilter_exec(plc_sThread* tp, pwr_sClass_Sim_LagFilter* plc_obj);
void Sim_LeadLagFilter_exec(
    plc_sThread* tp, pwr_sClass_Sim_LeadLagFilter* plc_obj);
void Sim_SouFilter_exec(plc_sThread* tp, pwr_sClass_Sim_SouFilter* plc_obj);
void Sim_SouTOoFilter_exec(
    plc_sThread* tp, pwr_sClass_Sim_SouTOoFilter* plc_obj);
void Sim_Delay_exec(plc_sThread* tp, pwr_sClass_Sim_Delay* plc_obj);
void Sim_SlewRateLimiter_exec(
    plc_sThread* tp, pwr_sClass_Sim_SlewRateLimiter* plc_obj);
void Sim_SignalGeneratorFo_init(pwr_sClass_Sim_SignalGeneratorFo* o);
void Sim_SignalGeneratorFo_exec(plc_sThread* tp, pwr_sClass_Sim_SignalGeneratorFo* o);
void Sim_CylinderTankFo_init(pwr_sClass_Sim_CylinderTankFo* o);
void Sim_CylinderTankFo_exec(plc_sThread* tp, pwr_sClass_Sim_CylinderTankFo* o);
void Sim_FurnaceFo_init(pwr_sClass_Sim_FurnaceFo* o);
void Sim_FurnaceFo_exec(plc_sThread* tp, pwr_sClass_Sim_FurnaceFo* o);

#endif
