include $(pwre_dir_symbols)

local_java_sources := \
	JopcNode.java, \
	JopcRemoteconfig.java, \
	JopcRemnodeudp.java, \
	JopcRemtrans.java, \
	JopcBackup_conf.java, \
	JopcDsfastconf.java, \
	JopcDstrendconf.java, \
	JopcIohandler.java, \
	JopcMessagehandler.java, \
	JopcChanai.java, \
	JopcChanao.java, \
	JopcChandi.java, \
	JopcChando.java, \
	JopcChanii.java, \
	JopcChanio.java, \
	JopcAvGen.java, \
	JopcAv.java, \
	JopcAiGen.java, \
	JopcAi.java, \
	JopcAoGen.java, \
	JopcAo.java, \
	JopcDvGen.java, \
	JopcDv.java, \
	JopcDiGen.java, \
	JopcDi.java, \
	JopcDoGen.java, \
	JopcDo.java, \
	JopcIvGen.java, \
	JopcIv.java, \
	JopcIiGen.java, \
	JopcIi.java, \
	JopcIoGen.java, \
	JopcIo.java, \
	JopcModeGen.java, \
	JopcMode.java, \
	JopcPidGen.java, \
	JopcPid.java, \
	JopcPlcthreadGen.java, \
	JopcPlcthread.java, \
	JopcPlcprocess.java, \
	JopcSysmonconfig.java, \
	JopcDisksup.java, \
	JopcBaseactuatora.java, \
	JopcBaseactuatora1.java, \
	JopcBaseactuatora2.java, \
	JopcBaseactuatora3.java, \
	JopcBaseactuatora4.java, \
	JopcBaseactuatora5.java, \
	JopcBaseactuatora6.java, \
	JopcBaseactuatora7.java, \
	JopcBasecircuitbreaker.java, \
	JopcBasecontactor.java, \
	JopcBasecontactor1.java, \
	JopcBasecvalve.java, \
	JopcBasecvalve1.java, \
	JopcBasecvalve2.java, \
	JopcBasecvalve3.java, \
	JopcBasecvalve4.java, \
	JopcBasecvalve5.java, \
	JopcBasecvalve6.java, \
	JopcBasecvalve7.java, \
	JopcBasedirvalve.java, \
	JopcBasefan.java, \
	JopcBaselevelsensor.java, \
	JopcBaselevelswitch.java, \
	JopcBasemanvalve.java, \
	JopcBasemanvalve1.java, \
	JopcBasemanvalve2.java, \
	JopcBasemanvalve3.java, \
	JopcBasemotor.java, \
	JopcBasemotor1.java, \
	JopcBasemotor2.java, \
	JopcBasemvalve.java, \
	JopcBasemvalve1.java, \
	JopcBasemvalve2.java, \
	JopcBasemvalve3.java, \
	JopcBasepositsensor.java, \
	JopcBasepressuresensor.java, \
	JopcBasepressureswitch.java, \
	JopcBasepropvalve.java, \
	JopcBasepump.java, \
	JopcBasesafetyswitch.java, \
	JopcBasesensor.java, \
	JopcBasesupswitch.java, \
	JopcBasetempsensor.java, \
	JopcBasetempswitch.java, \
	JopcBasevalve.java, \
	JopcBasefanaggr.java, \
	JopcRuntimecounter.java, \
	JopcAbb_acs800_1.java, \
	JopcAbb_acs800fanaggr.java, \
	JopcAbb_acs800motoraggr.java, \
	JopcAbb_acs800pumpaggr.java, \
	JopcSsab_safetyswitch.java

-include $(pwre_kroot)/tools/bld/src/$(os_name)/$(hw_name)/$(type_name)_generic.mk

ifeq ($($(type_name)_generic_mk),)
 -include $(pwre_kroot)/tools/bld/src/$(os_name)/$(type_name)_generic.mk
endif

ifeq ($($(type_name)_generic_mk),)
 include $(pwre_kroot)/tools/bld/src/$(type_name)_generic.mk
endif

-include ../../special.mk
-include ../special.mk
-include special.mk



