.TH pwr "1" "April 2005" "Proview" "Proview Manual"
.SH NAME
pwrsev - start and stop Proview Storage Environment
.SH SYNOPSIS
.B pwrsev 
[start][stop][restart][reset]
.SH DESCRIPTION
Start and stop command for Proview Storage Environment.

.SH OPTIONS
.HP
\fBstart\fR
.IP
Start Proview storage environment.

.HP
\fBstop\fR
.IP
Stop Proview storage environment.

.HP
\fBrestart\fR
.IP
Stop and start the Proview storage environment.

.HP
\fBreset\fR
.IP
Remove all processes and resources.

.SH FILES
/etc/pwrp_profile

The Proview system wide configuration file.

.SH ENVIRONMENT
.HP
PWR_BUS_ID
.IP
QCOM bus identity.
.SH AUTHOR
Written by cs.

.SH "SEE ALSO"
.BR sev_ini(1)

