#!/bin/bash
#
# Startscript för PWR
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
wrapper="/tmp/sev_ini_wrapper"
killer="/tmp/pwr_killer"

. /etc/pwrp_profile
umask 002

create_wrapper()
{
  if [ ! -e $wrapper ] ; then
    echo "#!/bin/bash" > $wrapper
    echo "source /etc/pwrp_profile" >> $wrapper
    echo "umask 002" >> $wrapper
    echo "\$pwr_exe/sev_ini \$* &" >> $wrapper
    chmod a+rx $wrapper
    if [ ! -e $wrapper ] ;then
      echo "$wrapper not writable, check permissions"
      exit
    fi
  fi
}

create_killer()
{
  if [ ! -e $killer ] ; then
    echo "#!/bin/bash" > $killer
    echo "source /etc/pwrp_profile" >> $killer
    echo "umask 002" >> $killer
    
    echo "kill -9 `ps ax | grep "rt_" | awk '{ print $1}'`" >> $killer
    echo "kill -9 `ps ax | grep "sev_" | awk '{ print $1}'`" >> $killer

    echo "eval `ipcs -s|grep ^0x|grep "[ \t]pwrp[ \t]"|awk '{printf "ipcrm sem %s;", $2}'`" >> $killer
    echo "eval `ipcs -q|grep ^0x|grep "[ \t]pwrp[ \t]"|awk '{printf "ipcrm msg %s;", $2}'`" >> $killer
    echo "eval `ipcs -m|grep ^0x|grep "[ \t]pwrp[ \t]"|awk '{printf "ipcrm shm %s;", $2}'`" >> $killer
    echo "rm /tmp/pwr*\$PWR_BUS_ID" >> $killer
    
    chmod a+rx $killer
    if [ ! -e $killer ] ;then
      echo "$killer not writable, check permissions"
      exit
    fi
  fi
}


pwr_start()
{
  create_wrapper
  if [ `whoami` == "pwrp" ];then
    $wrapper
  else
    sudo -u pwrp $wrapper
  fi
}

pwr_stop()
{
  create_wrapper
  if [ `whoami` == "pwrp" ];then
    $wrapper -s
    if [ -e $pwrp_exe/pwrp_stop.sh ]; then
      source $pwrp_exe/pwrp_stop.sh
    fi
  else
    sudo -u pwrp $wrapper -s
    if [ -e $pwrp_exe/pwrp_stop.sh ]; then
      sudo -u pwrp source $pwrp_exe/pwrp_stop.sh
    fi
  fi 
  while [ "`ps aux | grep -v grep | grep rt_`" != "" ] ; do sleep 1; done  
}

pwr_reload()
{
  if [ `whoami` == "pwrp" ];then
    $pwr_exe/sev_ini_wrapper -r
  else
    sudo -u pwrp $pwr_exe/sev_ini_wrapper -r
  fi
}

pwr_kill()
{
  create_killer
  if [ `whoami` == "pwrp" ];then
    $killer
  else
    sudo -u pwrp $killer
  fi 
}

case "$1"
  in
    start)
	echo "Startar PWR."
	pwr_start    
	echo "Klar."
      ;;
    stop)
	echo "Stoppar PWR..."
	pwr_stop
	echo "Klar"
      ;;
    restart)
	echo "Startar om PWR."
	echo "Stoppar det först."
	pwr_stop
	sleep 1
	echo "Startar igen."
	pwr_start
	echo "Klar."
	;;
    reload)
	echo "PWR varmomstart "
        pwr_reload
	echo "Klar."
	;;
    kill)
	echo "Tar bort delat minne och kvarblivna applikationer från PWR"
        pwr_kill
	echo "Klar."
	;;
    *)
	echo "Usage:{start|stop|restart|reload|kill}" >&2
        exit 1
	;;
  esac

exit 0
