#!/bin/bash
set -e
if [ "$pwrrt_xtrace" != "" ]; then
  set -o xtrace
fi

# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
        if [ -d /usr/doc -a ! -e /usr/doc/pwrtest -a -d /usr/share/doc/pwrtest ]; then
                ln -sf ../share/doc/pwrtest /usr/doc/pwrtest
        fi
fi
# End automatically added section

proot="/pwrp"
aroot="/usr/pwrp/adm"

# Create users...
echo "-- Creating users/groups..."
for grp in pwrp b55 b66 skiftel; do
  if getent group ${grp} >/dev/null; then
    echo "-- Group ${grp} already exist. OK!"
  else
    if groupadd ${grp}; then
      echo "-- Group ${grp} added..."
    fi
  fi
done

# Do we have a pwrp user already?
if getent passwd pwrp >/dev/null; then
  echo "-- User pwrp already exist. OK!"
else
  if useradd --create-home --shell /bin/bash --password aaupl/kQs1p3U --gid pwrp --groups b55,b66,skiftel --home-dir /home/pwrp pwrp; then
    echo "-- User pwrp added..."
  fi

  # If all went well we copy proview specific startup scripts to the home folder
  if [ -e /home/pwrp ]; then
    cp /usr/pwrsev/cnf/user/.rtt_start /home/pwrp
    chmod a+x /home/pwrp/.rtt_start
    cp /usr/pwrsev/cnf/user/.xtt_start /home/pwrp
    chmod a+x /home/pwrp/.xtt_start
  fi

  # Add pwrp to group dialout
  if getent group dialout >/dev/null; then
    usermod -a -G dialout pwrp && echo "-- User 'pwrp' added to group 'dialout'..." || echo "-- Unable to add user 'pwrp' to group 'dialout'!"
  fi
fi

if getent passwd skiftel >/dev/null; then
  echo "-- User skiftel already exist. OK!"
else
  if useradd --create-home --shell /bin/bash --password aa6NzxS/aBgP6 --gid skiftel --groups pwrp --home-dir /home/skiftel skiftel; then
    echo "-- User skiftel added..."
  fi

  # If all went well we copy proview specific startup scripts to the home folder
  if [ -e /home/skiftel ]; then
    cp /usr/pwrsev/cnf/user/.rtt_start /home/skiftel
    chmod a+x /home/skiftel/.rtt_start
    cp /usr/pwrsev/cnf/user/.xtt_start /home/skiftel
    chmod a+x /home/skiftel/.xtt_start

    # And change group ownership of skiftel's home folder to pwrp
    chgrp -R pwrp /home/skiftel
  fi
fi

# Setup the operator group memberships
groups="pwrp"
getent group audio >/dev/null && groups+=",audio"

# Add the user b55
if getent passwd b55 >/dev/null; then
   echo "-- User b55 already exist. OK!"
else
  if useradd --create-home --shell /bin/bash --password aaQPClsglxJP6 --gid b55 --groups $groups --home-dir /home/b55 b55; then
    echo "-- User b55 added..."
  fi

  if [ -e /home/b55 ]; then
    cp /usr/pwrsev/cnf/op/.rtt_start /home/b55
    chmod a+x /home/b55/.rtt_start
    cp /usr/pwrsev/cnf/op/.xtt_start /home/b55
    chmod a+x /home/b55/.xtt_start

    chown -R b55 /home/b55
    chgrp -R pwrp /home/b55
    chmod g+rws /home/b55
  fi
fi

# Add the user b66
if getent passwd b66 >/dev/null; then
   echo "-- User b66 already exist. OK!"
else
  if useradd --create-home --shell /bin/bash --password 1P4JdWA5HqSMQ --gid b66 --groups $groups --home-dir /home/b66 b66; then
    echo "-- User b66 added..."
  fi

  if [ -e /home/b66 ]; then
    cp /usr/pwrsev/cnf/op/.rtt_start /home/b66
    chmod a+x /home/b55/.rtt_start
    cp /usr/pwrsev/cnf/op/.xtt_start /home/b66
    chmod a+x /home/b55/.xtt_start

    chown -R b66 /home/b66
    chgrp -R pwrp /home/b66
    chmod g+rws /home/b66
  fi
fi

chown -R pwrp /usr/pwrsev
chgrp -R pwrp /usr/pwrsev

setcap cap_sys_nice,cap_sys_boot,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_net_broadcast=eip /usr/pwrrt/exe/sev_ini

# Source pwrp_profile in login shells
if [ ! -e /etc/profile/pwrp_profile.sh ]; then
  # profile.d should always exist on a modern debian system. BUT if it doesn't we create it :)
  if [ ! -e /etc/profile.d ]; then mkdir /etc/profile.d; fi
 	echo "[[ -e /etc/pwrp_profile ]] && . /etc/pwrp_profile" > /etc/profile.d/pwrp_profile.sh
fi

# Source pwrp_profile from both profile and bash.bashrc
# for cnf_file in /etc/profile /etc/bash.bashrc; do
#   if ! grep -q "/etc/pwrp_profile\b" ${cnf_file}; then
#   	cat >> ${cnf_file} <<-EOF
# 		[[ -e /etc/pwrp_profile ]] && . /etc/pwrp_profile
# 		EOF
#   fi
# done

# Copy configuration files
new_cnf=0
if [ ! -e /etc/proview.cnf ]; then
  cp /usr/pwrsev/cnf/proview.cnf /etc
  new_cnf=1
fi

# Create startup link
set +e
checklink=`eval ls /etc/rc2.d/S90pwrsev 2>/dev/null`
set -e
if [ "$checklink" != "" ]; then
  rm /etc/rc2.d/S90pwrsev
fi
ln -s /etc/init.d/pwrsev /etc/rc2.d/S90pwrsev

# Create project
new_project=0
if [ ! -e $proot ]; then
  new_project=1

  mkdir $proot
  mkdir $proot/common
  mkdir $proot/common/inc
  mkdir $proot/common/load
  mkdir $proot/common/log
  mkdir $proot/common/loghist
  mkdir $proot/common/db
  mkdir $proot/common/web
  mkdir $proot/x86_64_linux
  mkdir $proot/x86_64_linux/exe
  mkdir $proot/x86_64_linux/lib
  mkdir $proot/x86_64_linux/obj
  mkdir $proot/x86_64_linux/lis

  chown -R pwrp $proot
  chgrp -R pwrp $proot

fi

if [ ! -e $aroot/db ]; then
  mkdir -p $aroot/db
  chown -R pwrp $aroot
fi

#

changes=0
if [ $new_cnf -eq 1 ]; then
  changes=1
elif [ $new_project -eq 1 ]; then
  changes=1
fi

if [ $changes -ne 0 ]; then
  echo ""
  echo "***********************************************************"
  echo "  Don't forget to do this :"
  echo ""
fi

if [ $new_cnf -eq 1 ]; then
  echo "-- Enter QcomBusId in /etc/proview.cnf"
fi

if [ $new_project -eq 1 ]; then
  nodename=`eval uname -n`
  echo "-- Distribute project to $nodename"
fi

if [ $changes -ne 0 ]; then
  echo ""
  echo "***********************************************************"
  echo ""
fi
