/* 
 * Proview   Open Source Process Control.
 * Copyright (C) 2005-2013 SSAB EMEA AB.
 *
 * This file is part of Proview.
 *
 * This program is free software; you can redistribute it and/or 
 * modify it under the terms of the GNU General Public License as 
 * published by the Free Software Foundation, either version 2 of 
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with Proview. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking Proview statically or dynamically with other modules is
 * making a combined work based on Proview. Thus, the terms and 
 * conditions of the GNU General Public License cover the whole 
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * Proview give you permission to, from the build function in the
 * Proview Configurator, combine Proview with modules generated by the
 * Proview PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every 
 * copy of the combined work is accompanied by a complete copy of 
 * the source code of Proview (the version used to produce the 
 * combined work), being distributed under the terms of the GNU 
 * General Public License plus this exception.
 */

#ifndef rt_plc_proc_h
#define rt_plc_proc_h

/* Initialize the PLC.
   At this state only direct linking can be done.
   The part of the initialization which effects parameters
   in the object body must wait until the old PLC program has
   stopped. 
   First argument = 1 -> Do the direct link part.
   First argument = 0 -> It is ok to change object parameters.

   The part of the initialization which effects parameters
   in the object body can now be done, since the old PLC program has
   stopped. 
   First argument (DirectLink) = 2 -> Do the I/O direct link part.
   First argument (DirectLink) = 0 -> It is ok to change object parameters.  */


typedef struct plc_proctbl plc_sProctbl;

struct plc_proctbl {
  pwr_tObjid	thread;
  void		(*init)(int, plc_sThread*);
  void		(*exec)(int, plc_sThread*);
};
#endif
