/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2019 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

/* co_help_qt.cpp -- Help window */

#include <locale.h>

#include "co_help_qt.h"

#include "cow_qt_helpers.h"
#include "cow_style_qt.h"

#include <QApplication>

CoHelpQt* help;

void close_cb(void* ctx, void* xhelp)
{
  ((CoXHelpQt*)xhelp)->toplevel->close();
  delete help;
  exit(0);
}

int main(int argc, char* argv[])
{
  setDebug(1);
  int sts;

  QApplication app(argc, argv);
  QApplication::setStyle(new PwrStyle());

  setlocale(LC_NUMERIC, "POSIX");
  setlocale(LC_TIME, "en_US");

  help = new CoHelpQt(argc, argv, &sts);

  return app.exec();
}

CoHelpQt::~CoHelpQt()
{
  delete xhelp;
}

CoHelpQt::CoHelpQt(int argc, char* argv[], int* return_sts)
    : CoHelpMain(argc, argv, return_sts)
{
  pwr_tStatus sts;

  debug_print("%s ", argv[0]);
  for (int i = 1; i < argc; i++) {
    fprintf(stderr, "%s ", argv[i]);
  }
  fprintf(stderr, "\n");

  // Create help window
  xhelp = new CoXHelpQt(this, xhelp_eUtility_Xtt, &sts);
  // xhelp->open_URL_cb = open_URL_cb;
  CoXHelp::set_default(xhelp);
  xhelp->close_cb = close_cb;

  exec_help();
}