ARG RELEASE=debian:10
FROM $RELEASE
ARG INSTALL_UPDATE
ARG INSTALL_PWRRT
ARG PKG_PWRRT

COPY ./test_pwrtest01b.sh ./$PKG_PWRRT ./pwrp_pkg_pwrtest01b_0001.tgz ./
RUN $INSTALL_UPDATE
RUN $INSTALL_PWRRT
RUN apt-get install -y iproute2
RUN dpkg -i $PKG_PWRRT
RUN mv ./pwrp_pkg_pwrtest01b_0001.tgz /home/pwrp/
CMD ./test_pwrtest01b.sh
