#!/bin/bash
#
# ver='version' is added by build.sh
#

set -e
echo "Here in prerm..."
# Automatically added by dh_installdocs
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/pwrtest ]; then
        rm -f /usr/doc/pwrtest
fi
# End automatically added section

if [ -e /usr/pwrp/pwrdemo$ver ]; then
 rm -r /usr/pwrp/pwrdemo$ver
fi
