/* 
 * Proview   Open Source Process Control.
 * Copyright (C) 2005-2011 SSAB Oxelosund AB.
 *
 * This file is part of Proview.
 *
 * This program is free software; you can redistribute it and/or 
 * modify it under the terms of the GNU General Public License as 
 * published by the Free Software Foundation, either version 2 of 
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with Proview. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking Proview statically or dynamically with other modules is
 * making a combined work based on Proview. Thus, the terms and 
 * conditions of the GNU General Public License cover the whole 
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * Proview give you permission to, from the build function in the
 * Proview Configurator, combine Proview with modules generated by the
 * Proview PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every 
 * copy of the combined work is accompanied by a complete copy of 
 * the source code of Proview (the version used to produce the 
 * combined work), being distributed under the terms of the GNU 
 * General Public License plus this exception.
 */

#ifndef xtt_xcrr_motif_h
#define xtt_xcrr_motif_h

/* xtt_xcrr_motif.h -- Object crossreferences */

#ifndef xtt_xcrr_h
# include "xtt_xcrr.h"
#endif

class XCrrMotif : public XCrr {
  public:
    XCrrMotif( 
	Widget 		xa_parent_wid, 
	void 		*xa_parent_ctx, 
	pwr_sAttrRef 	*xa_objar,
	int 		xa_advanced_user,
	int             *xa_sts);
    ~XCrrMotif();
    Widget	parent_wid;
    Widget	brow_widget;
    Widget	form_widget;
    Widget	toplevel;
    Widget	xcrrnav_form;
    int		set_focus_disabled;
    XtIntervalId focus_timerid;

    void pop();

    static void activate_exit( Widget w, XCrr *xcrr, XmAnyCallbackStruct *data);
    static void activate_openplc( Widget w, XCrr *xcrr, XmAnyCallbackStruct *data);
    static void activate_help( Widget w, XCrr *xcrr, XmAnyCallbackStruct *data);
    static void create_xcrrnav_form( Widget w, XCrr *xcrr, XmAnyCallbackStruct *data);
    static void enable_set_focus( XCrrMotif *xcrr);
    static void disable_set_focus( XCrrMotif *xcrr, int time);
    static void action_inputfocus( Widget w, XmAnyCallbackStruct *data);

};

#endif







