#!/bin/bash
set -e
if [ "$pwrrt_xtrace" != "" ]; then
  set -o xtrace
fi

# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
        if [ -d /usr/doc -a ! -e /usr/doc/pwrtest -a -d /usr/share/doc/pwrtest ]; then
                ln -sf ../share/doc/pwrtest /usr/doc/pwrtest
        fi
fi
# End automatically added section

proot="/pwrp"
aroot="/usr/pwrp/adm"

# Create users...
echo "-- Creating users/groups..."
for grp in pwrp b55 b66 skiftel; do
  if getent group ${grp} >/dev/null; then
    echo "-- Group ${grp} already exist. OK!"
  else
    if groupadd ${grp}; then
      echo "-- Group ${grp} added..."
    fi
  fi
done

# Do we have a pwrp user already?
if getent passwd pwrp >/dev/null; then
  echo "-- User pwrp already exist. OK!"
else
  if useradd --create-home --shell /bin/bash --password aaupl/kQs1p3U --gid pwrp --groups b55,b66,skiftel --home-dir /home/pwrp pwrp; then
    echo "-- User pwrp added..."
  fi

  # If all went well we copy proview specific startup scripts to the home folder
  if [ -e /home/pwrp ]; then
    cp /usr/pwrrt/cnf/user/.rtt_start /home/pwrp
    chmod a+x /home/pwrp/.rtt_start
    cp /usr/pwrrt/cnf/user/.xtt_start /home/pwrp
    chmod a+x /home/pwrp/.xtt_start
  fi

  # Add pwrp to group dialout
  if getent group dialout >/dev/null; then
    usermod -a -G dialout pwrp && echo "-- User 'pwrp' added to group 'dialout'..." || echo "-- Unable to add user 'pwrp' to group 'dialout'!"
  fi
fi

if getent passwd skiftel >/dev/null; then
  echo "-- User skiftel already exist. OK!"
else
  if useradd --create-home --shell /bin/bash --password aa6NzxS/aBgP6 --gid skiftel --groups pwrp --home-dir /home/skiftel skiftel; then
    echo "-- User skiftel added..."
  fi

  # If all went well we copy proview specific startup scripts to the home folder
  if [ -e /home/skiftel ]; then
    cp /usr/pwrrt/cnf/user/.rtt_start /home/skiftel
    chmod a+x /home/skiftel/.rtt_start
    cp /usr/pwrrt/cnf/user/.xtt_start /home/skiftel
    chmod a+x /home/skiftel/.xtt_start

    # And change group ownership of skiftel's home folder to pwrp
    chgrp -R pwrp /home/skiftel
  fi
fi

# Setup the operator group memberships
groups="pwrp"
getent group audio >/dev/null && groups+=",audio"

# Add the user b55
if getent passwd b55 >/dev/null; then
   echo "-- User b55 already exist. OK!"
else
  if useradd --create-home --shell /bin/bash --password aaQPClsglxJP6 --gid b55 --groups $groups --home-dir /home/b55 b55; then
    echo "-- User b55 added..."
  fi

  if [ -e /home/b55 ]; then
    cp /usr/pwrrt/cnf/op/.rtt_start /home/b55
    chmod a+x /home/b55/.rtt_start
    cp /usr/pwrrt/cnf/op/.xtt_start /home/b55
    chmod a+x /home/b55/.xtt_start

    chown -R b55 /home/b55
    chgrp -R pwrp /home/b55
    chmod g+rws /home/b55
  fi
fi

# Add the user b66
if getent passwd b66 >/dev/null; then
   echo "-- User b66 already exist. OK!"
else
  if useradd --create-home --shell /bin/bash --password 1P4JdWA5HqSMQ --gid b66 --groups $groups --home-dir /home/b66 b66; then
    echo "-- User b66 added..."
  fi

  if [ -e /home/b66 ]; then
    cp /usr/pwrrt/cnf/op/.rtt_start /home/b66
    chmod a+x /home/b55/.rtt_start
    cp /usr/pwrrt/cnf/op/.xtt_start /home/b66
    chmod a+x /home/b55/.xtt_start

    chown -R b66 /home/b66
    chgrp -R pwrp /home/b66
    chmod g+rws /home/b66
  fi
fi

chown -R pwrp /usr/pwrrt
chgrp -R pwrp /usr/pwrrt

setcap cap_sys_nice,cap_sys_boot,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_net_broadcast=eip /usr/pwrrt/exe/rt_ini

# We shouldn't need any of the below file modifications but they are kept for reference in the meantime...
# ALCM should be fine with CAP_NET_RAW
# ProviewR should run as the user pwrp so rt_X apps are fine...?
# Realtime priorities and schedulers use CAP_SYS_NICE
# We also need CAP_SYS_BOOT for when one has chosen to reboot the runtime system on emergency break
# Processes that use serial ports should also be fine since pwrp is added to dialout during postinst...
# MODBUS is fine with CAP_NET_BIND_SERVICE

#chmod u+s /usr/pwrrt/exe/rt_ini
#chmod u+s /usr/pwrrt/exe/rt_rtt
#chmod u+s /usr/pwrrt/exe/rt_xtt
#chmod u+s /usr/pwrrt/exe/rt_bck
#chmod u+s /usr/pwrrt/exe/rt_gdhget
#chown root /usr/pwrrt/exe/rs_remote_alcm
#chmod u+s /usr/pwrrt/exe/rs_remote_alcm
#if getent group dialout > /dev/null; then
#  chgrp dialout /usr/pwrrt/exe/rs_remote_serial
#  chmod ug+s /usr/pwrrt/exe/rs_remote_serial
  #chgrp dialout /usr/pwrrt/exe/rs_remote_3964r
  #chmod ug+s /usr/pwrrt/exe/rs_remote_3964r
#fi
#if [ -e /usr/pwrrt/exe/rt_powerlink ]; then
  #chown root /usr/pwrrt/exe/rt_powerlink
  #chmod u+s /usr/pwrrt/exe/rt_powerlink
#fi
#chown root /usr/pwrrt/exe/rt_mozilla
#chmod u+s /usr/pwrrt/exe/rt_mozilla

# Copy configuration files
new_cnf=0
if [ ! -e /etc/proview.cnf ]; then
  cp /usr/pwrrt/cnf/proview.cnf /etc
  new_cnf=1
fi

# Source pwrp_profile in login shells
if [ ! -e /etc/profile/pwrp_profile.sh ]; then
  # profile.d should always exist on a modern debian system. BUT if it doesn't we create it :)
  if [ ! -e /etc/profile.d ]; then mkdir /etc/profile.d; fi
 	echo "[[ -e /etc/pwrp_profile ]] && . /etc/pwrp_profile" > /etc/profile.d/pwrp_profile.sh
fi

# Create startup link
# set +e
# checklink=`eval ls /etc/rc2.d/S90pwr 2>/dev/null`
# set -e
# if [ "$checklink" != "" ]; then
#   rm /etc/rc2.d/S90pwr
# fi
# ln -s /etc/init.d/pwr /etc/rc2.d/S90pwr

# set +e
# checklink=`eval ls /etc/rc2.d/S91gdhserver 2>/dev/null`
# set -e
# if [ "$checklink" != "" ]; then
#   rm /etc/rc2.d/S91gdhserver
# fi
# Obsolete
#ln -s /etc/init.d/gdhserver /etc/rc2.d/S91gdhserver

# Create project
new_project=0
if [ ! -e $proot ]; then
  new_project=1

  mkdir $proot
  mkdir $proot/common
  mkdir $proot/common/inc
  mkdir $proot/common/load
  mkdir $proot/common/log
  mkdir $proot/common/loghist
  mkdir $proot/common/db
  mkdir $proot/common/web
  mkdir $proot/x86_64_linux
  mkdir $proot/x86_64_linux/exe
  mkdir $proot/x86_64_linux/lib
  mkdir $proot/x86_64_linux/obj
  mkdir $proot/x86_64_linux/lis

  chown -R pwrp $proot
  chgrp -R pwrp $proot
  chmod g+w $proot/common/log

fi

if [ ! -e $aroot/db ]; then
  mkdir -p $aroot/db
  chown -R pwrp $aroot
fi

# Copy jar-files to web directory
if [ -e /etc/proview.cnf ]; then
  set +e
  web_dir=`eval cat /etc/proview.cnf | grep "\\bwebDirectory\\b" | awk '{print $2}'`
  set -e

  if [ -e "$web_dir" ]; then
    if [ -e /usr/pwrrt/lib/pwr_rt_client.jar ]; then
      cp /usr/pwrrt/lib/pwr_rt_client.jar $web_dir
      chown pwrp $web_dir/pwr_rt_client.jar
    fi
    if [ -e /usr/pwrrt/lib/pwr_jop.jar ]; then
      cp /usr/pwrrt/lib/pwr_jop.jar $web_dir
      chown pwrp $web_dir/pwr_jop.jar
    fi
    if [ -e /usr/pwrrt/lib/pwr_jopg.jar ]; then
      cp /usr/pwrrt/lib/pwr_jopg.jar $web_dir
      chown pwrp $web_dir/pwr_jopg.jar
    fi
  fi
fi

#
# Add proview web directories to Apache
#
if [ -e /etc/apache2/apache2.conf ]; then
  if ! egrep -q "Alias[ ]+/pwrp_web/" /etc/apache2/apache2.conf; then
    cat >> /etc/apache2/apache2.conf <<-EOF

	#
	# Proview alias pwrp_web, added by Proview installation
	#
	Alias /pwrp_web/ /pwrp/common/web/

	<Directory /pwrp/common/web>
	    AllowOverride None
	    Require all granted
	</Directory>
EOF
  fi

  if ! egrep -q "Alias[ ]+/pwrp_log/" /etc/apache2/apache2.conf; then
    cat >> /etc/apache2/apache2.conf <<-EOF

	#
	# Proview alias pwrp_log, added by Proview installation
	#
	Alias /pwrp_log/ /pwrp/common/log/

	<Directory /pwrp/common/log>
	    AllowOverride None
	    Require all granted
	</Directory>
EOF
  fi

  if ! egrep -q "Alias[ ]+/pwr_doc/" /etc/apache2/apache2.conf; then
    cat >> /etc/apache2/apache2.conf <<-EOF

	#
	# Proview alias pwr_doc, added by Proview installation
	#
	Alias /pwr_doc/ /usr/pwrrt/doc/

	<Directory /usr/pwrrt/doc>
	    AllowOverride None
	    Require all granted
	</Directory>
EOF
  fi
fi

# Add directories to nginx
if [ -e /etc/nginx/sites-available/default ]; then
  if ! egrep -q "location /pwrp_web/" /etc/nginx/sites-available/default; then
    awk '
BEGIN {
  inserver = 0;
  done = 0;
}
{
  if ( !done) {
    if ( substr( $0, 1, 1) != "#") {
      if ( $0 == "server {") {
        inserver = 1;
      }
      if ( inserver) {
        if ( $0 == "}") {
          printf("        # ProviewR directories\n");
          printf("        location /pwrp_web/ {\n");
          printf("          alias /pwrp/common/web/;\n");
          printf("        }\n");
          printf("        location /pwrp_log/ {\n");
          printf("          alias /pwrp/common/log/;\n");
          printf("        }\n");
          printf("        location /pwr_doc/ {\n");
          printf("          alias /usr/pwrrt/doc/;\n");
          printf("        }\n");
          printf("}\n");

          inserver = 0;
          done = 1;
        }
        else
          printf( "%s\n", $0);
      }
      else
        printf( "%s\n", $0);
    }
    else
      printf( "%s\n", $0);
  }
  else
    printf( "%s\n", $0);
}' /etc/nginx/sites-available/default > /etc/nginx/sites-available/default.new

    cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.old
    mv /etc/nginx/sites-available/default.new /etc/nginx/sites-available/default
    ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
  fi
fi

changes=0
if [ $new_cnf -eq 1 ]; then
  changes=1
elif [ $new_project -eq 1 ]; then
  changes=1
fi

echo ""
echo "***********************************************************"
echo "  Don't forget to do this :"
echo ""

if [ $new_cnf -eq 1 ]; then
  echo "-- Enter QcomBusId in /etc/proview.cnf"
fi

if [ $new_project -eq 1 ]; then
  nodename=`eval uname -n`
  echo "-- Distribute project to $nodename"
fi

echo "-- Once you have a project setup, enable the pwr service with:"
echo "   # systemctl enable pwr"
echo "***********************************************************"
echo ""
