#!/bin/sh
set -e

if [ "$pwrrt_xtrace" != "" ]; then
  set -o xtrace
fi

# Automatically added by dh_installdocs
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/pwrtest ]; then
        rm -f /usr/doc/pwrtest
fi
# End automatically added section

proot="/pwrp"
aroot="/usr/pwrp"

echo ""
echo -n "Do you want to remove project and users (y/n) [n] "
read remove_all
if [ "$remove_all" = "y" ]; then
  for user in pwrp skiftel b55 b66; do
    getent passwd ${user} >/dev/null 2>&1 && userdel -rf ${user} 2>/dev/null
    echo "-- Removed user ${user}"
  done
  for grp in pwrp skiftel b55 b66; do
    getent group ${grp} >/dev/null 2>&1 && groupdel ${grp}
    echo "-- Removed group ${grp}"
  done
  echo "-- Removing projects..."
  if [ -e $proot ]; then
    rm -r $proot && echo "-- Removed project $proot"
  fi
  if [ -e $aroot ]; then
    rm -r $aroot && echo "-- Removed admin directory $proot"
  fi
fi

systemctl disable pwr 2>/dev/null
if [ -e /etc/systemd/system/pwr.service ]; then
  rm /etc/systemd/system/pwr.service
  # Some symlinks are left in sysv after disabling pwr with systemd
  update-rc.d pwr remove >/dev/null 2>&1
fi

# Remove jar-files on web directory
if [ -e /etc/proview.cnf ]; then
  web_dir=`eval cat /etc/proview.cnf | grep "\\bwebDirectory\\b" | awk '{print $2}'`

  if [ -e $web_dir/pwr_rt_client.jar ]; then
    rm $web_dir/pwr_rt_client.jar
  fi
  if [ -e $web_dir/pwr_jop.jar ]; then
    rm $web_dir/pwr_jop.jar
  fi
  if [ -e $web_dir/pwr_jopg.jar ]; then
    rm $web_dir/pwr_jopg.jar
  fi
fi
