/*
 * Proview   Open Source Process Control.
 * Copyright (C) 2005-2017 SSAB EMEA AB.
 *
 * This file is part of Proview.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Proview. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking Proview statically or dynamically with other modules is
 * making a combined work based on Proview. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * Proview give you permission to, from the build function in the
 * Proview Configurator, combine Proview with modules generated by the
 * Proview PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of Proview (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#ifndef wb_xcrr_qt_h
#define wb_xcrr_qt_h

/* wb_xcrr_qt.h -- Object crossreferences */

#ifndef wb_ldh_h
# include "wb_ldh.h"
#endif

#include "flow.h"
#include "flow_browctx.h"
#include "flow_browapi.h"
#ifndef wb_xcrr_h
# include "wb_xcrr.h"
#endif

#ifndef cow_wow_qt_h
# include "cow_wow_qt.h"
#endif

class WCrrQtWidget;

class WCrrQt : public WCrr {
public:
  WCrrQt(QWidget *xa_parent_wid, void *xa_parent_ctx, ldh_tSesContext xa_ldhses,
         pwr_sAttrRef *xa_objar, int xa_advanced_user, int *xa_sts);
  QWidget *brow_widget;
  QWidget *form_widget;
  QWidget *xcrrnav_form;
  CoWowFocusTimerQt focustimer;

  void pop();
  void print();

private:
  WCrrQtWidget *toplevel;
};

class WCrrQtWidget : public QWidget {
  Q_OBJECT

public:
  WCrrQtWidget(WCrrQt *parent_ctx, QWidget *parent)
      : QWidget(parent, Qt::Window), crr(parent_ctx) {}

protected:
  void focusInEvent(QFocusEvent *event);
  void closeEvent(QCloseEvent *event);

public slots:
  void activate_openplc();
  void activate_help();

private:
  WCrrQt *crr;
};

#endif