
        .facility       LFU,304 /prefix = LFU__ ! 

success 	<successful completion>				/succ
nobootfile	<filename does not match bootfile syntax>	/error
vollist		<volume list syntax error>			/error
nofile		<unable to open file>				/error
plcversion	<plc version file corrupt>			/error
syntax		<syntax error> 					/error
nodename	<node does not exist>				/error
filecrp		<file is corrupt>				/error
