!  wb_pwrb_msg.msg -- work bench base classes messages
!
!  PROVIEW/R
!  Copyright (C) 1996 by Comator Process AB.
!
!  This module contains the defintion of the error messages used
!  in pwrb modules.
!
.facility       PWRB,3 /prefix = PWRB__	! Base Meta Data

success		<successful completion>					/succ
chanclass	<channel class not allowed on this card>		/error
alochan		<could not allocate a new channel>			/error
graphaction     <no action defined in graph object>                      /error
