!  wb_vldh_msg.msg -- very local datahandler
!
!  PROVIEW/R
!  Copyright (C) 1996 by Comator Process AB.
!
!  <Description>.
!
        .facility       VLDH,260 /prefix = VLDH__ ! Gre data handler

success		<successful completion>					/succ
nonodes		<no nodes found>					/info
nocons		<no connections found>					/info
nowinds		<no windows found>					/info
badobjtype	<object type out of range>				/error
badconpoint	<connection point out of range>				/error
objnotfound	<object not found>					/error
plcnotsaved	<plcprogram object is not saved>			/error
parentnotsaved	<parent node is  not saved>				/error


	.end
