
        .facility       WDA,316 /prefix = WDA__ ! 

success 	<successful completion>				/succ
noattrsel	<No attribute is selected>			/error
attrnoedit	<Attribute is noedit>				/error
stringtolong	<String is to long>				/error
input_syntax	<Input syntax error>				/error
noedit		<Not in edit mode>				/error
flagnoedit	<Noedit attribute>				/error
flagstate	<State attribute>				/error
disappeard	<Item has disappeard>				/error
nochildren	<Item has no children>				/error
attrnotfound	<Attribute is not found>			/error
attrinvalid	<Invalid attribute type>			/error
attrinvisible	<Attribute invisible>				/error
nonextattr	<No next attribute>				/error
noprevattr	<No previous attribute>				/error