
        .facility       WATT,309 /prefix = WATT__ ! 

success 	<successful completion>				/succ
noattrsel	<No attribute is selected>			/error
attrnoedit	<Attribute is noedit>				/error
stringtolong	<String is to long>				/error
input_syntax	<Input syntax error>				/error
noedit		<Not in edit mode>				/error
flagnoedit	<Noedit attribute>				/error
flagstate	<State attribute>				/error
disappeard	<Item has disappeard>				/error
nochildren	<Item has no children>				/error
attrnotfound	<Attribute is not found>			/error