/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2019 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#ifndef co_ctx_h
#define co_ctx_h

/* cnv_ctx.h -- Setup */

#include <string>
#include <vector>

#include "cnv_setup.h"

class CnvWblTo;
class CnvReadWbl;
class CnvReadXtthelp;

class CnvCtx {
  private:
  std::vector<std::string> depend;

  public:
  CnvCtx();
  pwr_tFileName dir;
  int generate_html;
  int generate_xtthelp;
  int generate_src;
  int generate_struct;
  int generate_ps;
  int generate_pdf;
  int generate_cdp;
  int common_structfile_only;
  int hpp;
  int verbose;
  pwr_tFileName setup_filename;
  pwr_tFileName depend_filename;
  pwr_tFileName dependfile;
  int first_class;
  CnvSetup* setup;
  CnvWblTo* wblto;
  CnvReadWbl* rw;
  CnvReadXtthelp* rx;

  void add_depend(char* dname);
  void set_dependfile(char* dname);
  void print_depend();

  static int read_line(char* line, int maxsize, FILE* file);
  static char* low(const char* in);
};

#endif
