#!/bin/bash
#
# Proview   Open Source Process Control.
# Copyright (C) 2005-2016 SSAB EMEA AB.
#
# This file is part of Proview.
#
# This program is free software; you can redistribute it and/or 
# modify it under the terms of the GNU General Public License as 
# published by the Free Software Foundation, either version 2 of 
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License 
# along with Proview. If not, see <http://www.gnu.org/licenses/>
#
# Linking Proview statically or dynamically with other modules is
# making a combined work based on Proview. Thus, the terms and 
# conditions of the GNU General Public License cover the whole 
# combination.
#
# In addition, as a special exception, the copyright holders of
# Proview give you permission to, from the build function in the
# Proview Configurator, combine Proview with modules generated by the
# Proview PLC Editor to a PLC program, regardless of the license
# terms of these modules. You may copy and distribute the resulting
# combined work under the terms of your choice, provided that every 
# copy of the combined work is accompanied by a complete copy of 
# the source code of Proview (the version used to produce the 
# combined work), being distributed under the terms of the GNU 
# General Public License plus this exception.
#

if [ -z $1 ]; then
  echo ""
  echo " jpwr_opwind.sh   Start java operator environment."
  echo ""
  echo " Arguments: Name of OpPlaceWeb object"
  echo ""
  echo " Example"
  echo ""
  echo " > jpwr_opwind.sh Nodes-DemoNode-OpPlaces-Web"
  echo ""
  exit;
fi

# Get systemname from bootfile
zero="0000"
nname=`eval uname -n`
nname=${nname%%.*}

bootfile=$pwrp_load/ld_boot_${nname}_${zero:0:4-${#PWR_BUS_ID}}${PWR_BUS_ID}.dat

if [ ! -e "$bootfile" ]; then
  echo "Unable to find bootfile: $bootfile"
  exit;
fi

let i=0
while read line; do
 if [ $i -eq 1 ]; then
   systemname=$line
   break;
 fi
 let i=$i+1
done < $bootfile

echo $systemname

export CLASSPATH=$pwr_lib/pwr_rt.jar:$pwr_lib/pwr_jop.jar:$pwr_lib/pwr_jopg.jar:$pwr_lib/pwr_jopc.jar:$pwr_lib/pwr_bcomp.jar:$pwr_lib/pwr_bcompfc.jar:$pwr_lib/pwr_abb.jar:$pwrp_lib/pwrp_$systemname.jar
export LD_LIBRARY_PATH=$pwr_exe
$jdk/bin/java jpwr.jop.JopOp $1
