include $(pwre_dir_symbols)

local_java_sources := \
        JopcAbb_acs800_1param.java, \
        JopcAbb_acs800_1.java, \
        JopcAbb_acs800fanaggr10.java, \
        JopcAbb_acs800fanaggr11.java, \
        JopcAbb_acs800fanaggr12.java, \
        JopcAbb_acs800fanaggr13.java, \
        JopcAbb_acs800fanaggr14.java, \
        JopcAbb_acs800fanaggr15.java, \
        JopcAbb_acs800fanaggr16.java, \
        JopcAbb_acs800fanaggr17.java, \
        JopcAbb_acs800fanaggr18.java, \
        JopcAbb_acs800fanaggr19.java, \
        JopcAbb_acs800fanaggr1.java, \
        JopcAbb_acs800fanaggr20.java, \
        JopcAbb_acs800fanaggr21.java, \
        JopcAbb_acs800fanaggr22.java, \
        JopcAbb_acs800fanaggr23.java, \
        JopcAbb_acs800fanaggr2.java, \
        JopcAbb_acs800fanaggr3.java, \
        JopcAbb_acs800fanaggr4.java, \
        JopcAbb_acs800fanaggr5.java, \
        JopcAbb_acs800fanaggr6.java, \
        JopcAbb_acs800fanaggr7.java, \
        JopcAbb_acs800fanaggr8.java, \
        JopcAbb_acs800fanaggr9.java, \
        JopcAbb_acs800fanaggr.java, \
        JopcAbb_acs800motoraggr10.java, \
        JopcAbb_acs800motoraggr11.java, \
        JopcAbb_acs800motoraggr12.java, \
        JopcAbb_acs800motoraggr13.java, \
        JopcAbb_acs800motoraggr14.java, \
        JopcAbb_acs800motoraggr15.java, \
        JopcAbb_acs800motoraggr16.java, \
        JopcAbb_acs800motoraggr17.java, \
        JopcAbb_acs800motoraggr18.java, \
        JopcAbb_acs800motoraggr19.java, \
        JopcAbb_acs800motoraggr1.java, \
        JopcAbb_acs800motoraggr20.java, \
        JopcAbb_acs800motoraggr21.java, \
        JopcAbb_acs800motoraggr22.java, \
        JopcAbb_acs800motoraggr23.java, \
        JopcAbb_acs800motoraggr2.java, \
        JopcAbb_acs800motoraggr3.java, \
        JopcAbb_acs800motoraggr4.java, \
        JopcAbb_acs800motoraggr5.java, \
        JopcAbb_acs800motoraggr6.java, \
        JopcAbb_acs800motoraggr7.java, \
        JopcAbb_acs800motoraggr8.java, \
        JopcAbb_acs800motoraggr9.java, \
        JopcAbb_acs800motoraggr.java, \
        JopcAbb_acs800pumpaggr10.java, \
        JopcAbb_acs800pumpaggr11.java, \
        JopcAbb_acs800pumpaggr12.java, \
        JopcAbb_acs800pumpaggr13.java, \
        JopcAbb_acs800pumpaggr14.java, \
        JopcAbb_acs800pumpaggr15.java, \
        JopcAbb_acs800pumpaggr16.java, \
        JopcAbb_acs800pumpaggr17.java, \
        JopcAbb_acs800pumpaggr18.java, \
        JopcAbb_acs800pumpaggr19.java, \
        JopcAbb_acs800pumpaggr1.java, \
        JopcAbb_acs800pumpaggr20.java, \
        JopcAbb_acs800pumpaggr21.java, \
        JopcAbb_acs800pumpaggr22.java, \
        JopcAbb_acs800pumpaggr23.java, \
        JopcAbb_acs800pumpaggr2.java, \
        JopcAbb_acs800pumpaggr3.java, \
        JopcAbb_acs800pumpaggr4.java, \
        JopcAbb_acs800pumpaggr5.java, \
        JopcAbb_acs800pumpaggr6.java, \
        JopcAbb_acs800pumpaggr7.java, \
        JopcAbb_acs800pumpaggr8.java, \
        JopcAbb_acs800pumpaggr9.java, \
        JopcAbb_acs800pumpaggr.java

-include $(pwre_kroot)/tools/bld/src/$(os_name)/$(hw_name)/$(type_name)_generic.mk

ifeq ($($(type_name)_generic_mk),)
 -include $(pwre_kroot)/tools/bld/src/$(os_name)/$(type_name)_generic.mk
endif

ifeq ($($(type_name)_generic_mk),)
 include $(pwre_kroot)/tools/bld/src/$(type_name)_generic.mk
endif

-include ../../special.mk
-include ../special.mk
-include special.mk



