/*
 * ProviewR   Open Source Process Control.
 * Copyright (C) 2005-2019 SSAB EMEA AB.
 *
 * This file is part of ProviewR.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ProviewR. If not, see <http://www.gnu.org/licenses/>
 *
 * Linking ProviewR statically or dynamically with other modules is
 * making a combined work based on ProviewR. Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * In addition, as a special exception, the copyright holders of
 * ProviewR give you permission to, from the build function in the
 * ProviewR Configurator, combine ProviewR with modules generated by the
 * ProviewR PLC Editor to a PLC program, regardless of the license
 * terms of these modules. You may copy and distribute the resulting
 * combined work under the terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of
 * the source code of ProviewR (the version used to produce the
 * combined work), being distributed under the terms of the GNU
 * General Public License plus this exception.
 */

#ifndef xtt_eveve_qt_h
#define xtt_eveve_qt_h

/* xtt_eveve_qt.h -- Alarm window in xtt */

#include "xtt_eveve.h"

#include <QVBoxLayout>
#include <QWidget>

class EvEveQtWidget;

class EvEveQt : public EvEve {
public:
  EvEveQt(void* ev_parent_ctx, QWidget* ev_parent_wid, char* eve_name,
      pwr_tObjid ev_user, int ev_eventname_seg, int ev_width, int ev_height,
      int ev_x, int ev_y, pwr_tObjid ev_view, unsigned int ev_options,
      void* widget, pwr_tStatus* status);
  ~EvEveQt();

  EvEveQtWidget* toplevel;
  QWidget* parent_wid_ala;
  QWidget* eve_widget;
  QVBoxLayout* eve_vbox;
  pwr_tObjid alarm_views[25];

  void map_ala();
  void unmap_ala();
  void set_title_ala(char* title);

  QWidget* get_widget()
  {
    return parent_wid_ala;
  }
};

class EvEveQtWidget : public QWidget {
  Q_OBJECT

public:
  EvEveQtWidget(EvEveQt* parent_ctx, QWidget* parent)
      : QWidget(), eve(parent_ctx)
  {
  }

protected:
  void focusInEvent(QFocusEvent* event);
  void closeEvent(QCloseEvent* event);

public slots:
  void eve_activate_print();
  void eve_activate_zoom_in();
  void eve_activate_zoom_out();
  void eve_activate_zoom_reset();
  void eve_activate_open_plc();
  void eve_activate_display_in_xnav();
  void eve_activate_disp_hundredth(bool set);
  void eve_activate_hide_object(bool set);
  void eve_activate_hide_text(bool set);
  void eve_activate_help();
  void eve_activate_helpevent();
  void eve_activate_shift_view();
  void eve_activate_select_flat();
  void eve_activate_select_view();

private:
  EvEveQt* eve;
};

#endif